# generated by datamodel-codegen:
#   filename:  order.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class OrderStatusPayload(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
        populate_by_name=True,
    )
    id: str | None = Field(None, title="Id")
    account: str | None = Field(None, title="Account")
    symbol: str | None = Field(None, title="Symbol")
    identifier: str | None = Field(None, title="Identifier")
    name: str | None = Field(None, title="Name")
    sec_type: str | None = Field(None, alias="secType", title="Sectype")
    market: str | None = Field(None, title="Market")
    currency: str | None = Field(None, title="Currency")
    multiplier: float | None = Field(None, title="Multiplier")
    expiry: str | None = Field(None, title="Expiry")
    strike: str | None = Field(None, title="Strike")
    right: str | None = Field(None, title="Right")
    action: str | None = Field(None, title="Action")
    order_type: str | None = Field(None, alias="orderType", title="Ordertype")
    time_in_force: str | None = Field(None, alias="timeInForce", title="Timeinforce")
    is_long: bool | None = Field(None, alias="isLong", title="Islong")
    outside_rth: bool | None = Field(None, alias="outsideRth", title="Outsiderth")
    total_quantity: int | None = Field(None, alias="totalQuantity", title="Totalquantity")
    total_quantity_scale: int | None = Field(
        None, alias="totalQuantityScale", title="Totalquantityscale"
    )
    limit_price: float | None = Field(None, alias="limitPrice", title="Limitprice")
    stop_price: float | None = Field(None, alias="stopPrice", title="Stopprice")
    total_cash_amount: float | None = Field(None, alias="totalCashAmount", title="Totalcashamount")
    filled_quantity: int | None = Field(None, alias="filledQuantity", title="Filledquantity")
    filled_quantity_scale: int | None = Field(
        None, alias="filledQuantityScale", title="Filledquantityscale"
    )
    avg_fill_price: float | None = Field(None, alias="avgFillPrice", title="Avgfillprice")
    filled_cash_amount: float | None = Field(
        None, alias="filledCashAmount", title="Filledcashamount"
    )
    commission_and_fee: float | None = Field(
        None, alias="commissionAndFee", title="Commissionandfee"
    )
    realized_pnl: float | None = Field(None, alias="realizedPnl", title="Realizedpnl")
    status: str | None = Field(None, title="Status")
    replace_status: str | None = Field(None, alias="replaceStatus", title="Replacestatus")
    cancel_status: str | None = Field(None, alias="cancelStatus", title="Cancelstatus")
    can_modify: bool | None = Field(None, alias="canModify", title="Canmodify")
    can_cancel: bool | None = Field(None, alias="canCancel", title="Cancancel")
    liquidation: bool | None = Field(None, title="Liquidation")
    error_msg: str | None = Field(None, alias="errorMsg", title="Errormsg")
    open_time: int | None = Field(None, alias="openTime", title="Opentime")
    timestamp: int | None = Field(None, title="Timestamp")
    source: str | None = Field(None, title="Source")
    user_mark: str | None = Field(None, alias="userMark", title="Usermark")
    seg_type: str | None = Field(None, alias="segType", title="Segtype")
    attr_desc: str | None = Field(None, alias="attrDesc", title="Attrdesc")
    gst: float | None = Field(None, title="Gst")


class OrderStatusEvent(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
        populate_by_name=True,
    )
    account: str = Field(..., description="Tiger Brokers account identifier.", title="Account")
    timestamp: str | None = Field(
        None,
        description="Event timestamp from Tiger Brokers (epoch milliseconds as string).",
        title="Timestamp",
    )
    received_at: AwareDatetime = Field(
        ...,
        description="ISO 8601 timestamp when the event was received by the subscriber.",
        title="Received At",
    )
    payload: OrderStatusPayload = Field(..., description="Order status payload.")
