# generated by datamodel-codegen:
#   filename:  transaction.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class TransactionPayload(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
        populate_by_name=True,
    )
    id: str | None = Field(None, title="Id")
    order_id: str | None = Field(None, alias="orderId", title="Orderid")
    account: str | None = Field(None, title="Account")
    symbol: str | None = Field(None, title="Symbol")
    identifier: str | None = Field(None, title="Identifier")
    multiplier: float | None = Field(None, title="Multiplier")
    action: str | None = Field(None, title="Action")
    market: str | None = Field(None, title="Market")
    currency: str | None = Field(None, title="Currency")
    seg_type: str | None = Field(None, alias="segType", title="Segtype")
    sec_type: str | None = Field(None, alias="secType", title="Sectype")
    filled_price: float | None = Field(None, alias="filledPrice", title="Filledprice")
    filled_quantity: int | None = Field(None, alias="filledQuantity", title="Filledquantity")
    create_time: int | None = Field(None, alias="createTime", title="Createtime")
    update_time: int | None = Field(None, alias="updateTime", title="Updatetime")
    transact_time: int | None = Field(None, alias="transactTime", title="Transacttime")
    timestamp: int | None = Field(None, title="Timestamp")


class TransactionEvent(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
        populate_by_name=True,
    )
    account: str = Field(..., description="Tiger Brokers account identifier.", title="Account")
    timestamp: str | None = Field(
        None,
        description="Event timestamp from Tiger Brokers (epoch milliseconds as string).",
        title="Timestamp",
    )
    received_at: str = Field(
        ...,
        description="ISO 8601 timestamp when the event was received by the subscriber.",
        title="Received At",
    )
    payload: TransactionPayload = Field(..., description="Transaction payload.")
